/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentStudentIndexRouteImport } from './routes/_student.student.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as StudentStudentSeatsRouteImport } from './routes/_student.student.seats'
import { Route as StudentStudentReservationsRouteImport } from './routes/_student.student.reservations'
import { Route as StudentStudentProfileRouteImport } from './routes/_student.student.profile'
import { Route as StudentStudentMyBooksRouteImport } from './routes/_student.student.my-books'
import { Route as StudentStudentLostBooksRouteImport } from './routes/_student.student.lost-books'
import { Route as StudentStudentFinesRouteImport } from './routes/_student.student.fines'
import { Route as AdminAdminStudentsRouteImport } from './routes/_admin.admin.students'
import { Route as AdminAdminSeatsRouteImport } from './routes/_admin.admin.seats'
import { Route as AdminAdminReservationsRouteImport } from './routes/_admin.admin.reservations'
import { Route as AdminAdminRequestsRouteImport } from './routes/_admin.admin.requests'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin.reports'
import { Route as AdminAdminLostBooksRouteImport } from './routes/_admin.admin.lost-books'
import { Route as AdminAdminIssuesRouteImport } from './routes/_admin.admin.issues'
import { Route as AdminAdminFinesRouteImport } from './routes/_admin.admin.fines'
import { Route as StudentStudentCatalogIndexRouteImport } from './routes/_student.student.catalog.index'
import { Route as AdminAdminCatalogIndexRouteImport } from './routes/_admin.admin.catalog.index'
import { Route as StudentStudentCatalogIdRouteImport } from './routes/_student.student.catalog.$id'
import { Route as AdminAdminCatalogIdRouteImport } from './routes/_admin.admin.catalog.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentIndexRoute = StudentStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentStudentSeatsRoute = StudentStudentSeatsRouteImport.update({
  id: '/student/seats',
  path: '/student/seats',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentReservationsRoute =
  StudentStudentReservationsRouteImport.update({
    id: '/student/reservations',
    path: '/student/reservations',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentMyBooksRoute = StudentStudentMyBooksRouteImport.update({
  id: '/student/my-books',
  path: '/student/my-books',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentLostBooksRoute = StudentStudentLostBooksRouteImport.update({
  id: '/student/lost-books',
  path: '/student/lost-books',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentFinesRoute = StudentStudentFinesRouteImport.update({
  id: '/student/fines',
  path: '/student/fines',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSeatsRoute = AdminAdminSeatsRouteImport.update({
  id: '/admin/seats',
  path: '/admin/seats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReservationsRoute = AdminAdminReservationsRouteImport.update({
  id: '/admin/reservations',
  path: '/admin/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRequestsRoute = AdminAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLostBooksRoute = AdminAdminLostBooksRouteImport.update({
  id: '/admin/lost-books',
  path: '/admin/lost-books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIssuesRoute = AdminAdminIssuesRouteImport.update({
  id: '/admin/issues',
  path: '/admin/issues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFinesRoute = AdminAdminFinesRouteImport.update({
  id: '/admin/fines',
  path: '/admin/fines',
  getParentRoute: () => AdminRoute,
} as any)
const StudentStudentCatalogIndexRoute =
  StudentStudentCatalogIndexRouteImport.update({
    id: '/student/catalog/',
    path: '/student/catalog/',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminAdminCatalogIndexRoute = AdminAdminCatalogIndexRouteImport.update({
  id: '/admin/catalog/',
  path: '/admin/catalog/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentStudentCatalogIdRoute = StudentStudentCatalogIdRouteImport.update({
  id: '/student/catalog/$id',
  path: '/student/catalog/$id',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminCatalogIdRoute = AdminAdminCatalogIdRouteImport.update({
  id: '/admin/catalog/$id',
  path: '/admin/catalog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/fines': typeof AdminAdminFinesRoute
  '/admin/issues': typeof AdminAdminIssuesRoute
  '/admin/lost-books': typeof AdminAdminLostBooksRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/reservations': typeof AdminAdminReservationsRoute
  '/admin/seats': typeof AdminAdminSeatsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/student/fines': typeof StudentStudentFinesRoute
  '/student/lost-books': typeof StudentStudentLostBooksRoute
  '/student/my-books': typeof StudentStudentMyBooksRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/reservations': typeof StudentStudentReservationsRoute
  '/student/seats': typeof StudentStudentSeatsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/student/': typeof StudentStudentIndexRoute
  '/admin/catalog/$id': typeof AdminAdminCatalogIdRoute
  '/student/catalog/$id': typeof StudentStudentCatalogIdRoute
  '/admin/catalog/': typeof AdminAdminCatalogIndexRoute
  '/student/catalog/': typeof StudentStudentCatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/fines': typeof AdminAdminFinesRoute
  '/admin/issues': typeof AdminAdminIssuesRoute
  '/admin/lost-books': typeof AdminAdminLostBooksRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/reservations': typeof AdminAdminReservationsRoute
  '/admin/seats': typeof AdminAdminSeatsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/student/fines': typeof StudentStudentFinesRoute
  '/student/lost-books': typeof StudentStudentLostBooksRoute
  '/student/my-books': typeof StudentStudentMyBooksRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/reservations': typeof StudentStudentReservationsRoute
  '/student/seats': typeof StudentStudentSeatsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/student': typeof StudentStudentIndexRoute
  '/admin/catalog/$id': typeof AdminAdminCatalogIdRoute
  '/student/catalog/$id': typeof StudentStudentCatalogIdRoute
  '/admin/catalog': typeof AdminAdminCatalogIndexRoute
  '/student/catalog': typeof StudentStudentCatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/auth': typeof AuthRoute
  '/_admin/admin/fines': typeof AdminAdminFinesRoute
  '/_admin/admin/issues': typeof AdminAdminIssuesRoute
  '/_admin/admin/lost-books': typeof AdminAdminLostBooksRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/requests': typeof AdminAdminRequestsRoute
  '/_admin/admin/reservations': typeof AdminAdminReservationsRoute
  '/_admin/admin/seats': typeof AdminAdminSeatsRoute
  '/_admin/admin/students': typeof AdminAdminStudentsRoute
  '/_student/student/fines': typeof StudentStudentFinesRoute
  '/_student/student/lost-books': typeof StudentStudentLostBooksRoute
  '/_student/student/my-books': typeof StudentStudentMyBooksRoute
  '/_student/student/profile': typeof StudentStudentProfileRoute
  '/_student/student/reservations': typeof StudentStudentReservationsRoute
  '/_student/student/seats': typeof StudentStudentSeatsRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_student/student/': typeof StudentStudentIndexRoute
  '/_admin/admin/catalog/$id': typeof AdminAdminCatalogIdRoute
  '/_student/student/catalog/$id': typeof StudentStudentCatalogIdRoute
  '/_admin/admin/catalog/': typeof AdminAdminCatalogIndexRoute
  '/_student/student/catalog/': typeof StudentStudentCatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/fines'
    | '/admin/issues'
    | '/admin/lost-books'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/reservations'
    | '/admin/seats'
    | '/admin/students'
    | '/student/fines'
    | '/student/lost-books'
    | '/student/my-books'
    | '/student/profile'
    | '/student/reservations'
    | '/student/seats'
    | '/admin/'
    | '/student/'
    | '/admin/catalog/$id'
    | '/student/catalog/$id'
    | '/admin/catalog/'
    | '/student/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/fines'
    | '/admin/issues'
    | '/admin/lost-books'
    | '/admin/reports'
    | '/admin/requests'
    | '/admin/reservations'
    | '/admin/seats'
    | '/admin/students'
    | '/student/fines'
    | '/student/lost-books'
    | '/student/my-books'
    | '/student/profile'
    | '/student/reservations'
    | '/student/seats'
    | '/admin'
    | '/student'
    | '/admin/catalog/$id'
    | '/student/catalog/$id'
    | '/admin/catalog'
    | '/student/catalog'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/auth'
    | '/_admin/admin/fines'
    | '/_admin/admin/issues'
    | '/_admin/admin/lost-books'
    | '/_admin/admin/reports'
    | '/_admin/admin/requests'
    | '/_admin/admin/reservations'
    | '/_admin/admin/seats'
    | '/_admin/admin/students'
    | '/_student/student/fines'
    | '/_student/student/lost-books'
    | '/_student/student/my-books'
    | '/_student/student/profile'
    | '/_student/student/reservations'
    | '/_student/student/seats'
    | '/_admin/admin/'
    | '/_student/student/'
    | '/_admin/admin/catalog/$id'
    | '/_student/student/catalog/$id'
    | '/_admin/admin/catalog/'
    | '/_student/student/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student/': {
      id: '/_student/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentStudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/student/seats': {
      id: '/_student/student/seats'
      path: '/student/seats'
      fullPath: '/student/seats'
      preLoaderRoute: typeof StudentStudentSeatsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/reservations': {
      id: '/_student/student/reservations'
      path: '/student/reservations'
      fullPath: '/student/reservations'
      preLoaderRoute: typeof StudentStudentReservationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/profile': {
      id: '/_student/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/my-books': {
      id: '/_student/student/my-books'
      path: '/student/my-books'
      fullPath: '/student/my-books'
      preLoaderRoute: typeof StudentStudentMyBooksRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/lost-books': {
      id: '/_student/student/lost-books'
      path: '/student/lost-books'
      fullPath: '/student/lost-books'
      preLoaderRoute: typeof StudentStudentLostBooksRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/fines': {
      id: '/_student/student/fines'
      path: '/student/fines'
      fullPath: '/student/fines'
      preLoaderRoute: typeof StudentStudentFinesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/students': {
      id: '/_admin/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/seats': {
      id: '/_admin/admin/seats'
      path: '/admin/seats'
      fullPath: '/admin/seats'
      preLoaderRoute: typeof AdminAdminSeatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reservations': {
      id: '/_admin/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminAdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/requests': {
      id: '/_admin/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminAdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/lost-books': {
      id: '/_admin/admin/lost-books'
      path: '/admin/lost-books'
      fullPath: '/admin/lost-books'
      preLoaderRoute: typeof AdminAdminLostBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/issues': {
      id: '/_admin/admin/issues'
      path: '/admin/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AdminAdminIssuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/fines': {
      id: '/_admin/admin/fines'
      path: '/admin/fines'
      fullPath: '/admin/fines'
      preLoaderRoute: typeof AdminAdminFinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/student/catalog/': {
      id: '/_student/student/catalog/'
      path: '/student/catalog'
      fullPath: '/student/catalog/'
      preLoaderRoute: typeof StudentStudentCatalogIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/catalog/': {
      id: '/_admin/admin/catalog/'
      path: '/admin/catalog'
      fullPath: '/admin/catalog/'
      preLoaderRoute: typeof AdminAdminCatalogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/student/catalog/$id': {
      id: '/_student/student/catalog/$id'
      path: '/student/catalog/$id'
      fullPath: '/student/catalog/$id'
      preLoaderRoute: typeof StudentStudentCatalogIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/catalog/$id': {
      id: '/_admin/admin/catalog/$id'
      path: '/admin/catalog/$id'
      fullPath: '/admin/catalog/$id'
      preLoaderRoute: typeof AdminAdminCatalogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminFinesRoute: typeof AdminAdminFinesRoute
  AdminAdminIssuesRoute: typeof AdminAdminIssuesRoute
  AdminAdminLostBooksRoute: typeof AdminAdminLostBooksRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminRequestsRoute: typeof AdminAdminRequestsRoute
  AdminAdminReservationsRoute: typeof AdminAdminReservationsRoute
  AdminAdminSeatsRoute: typeof AdminAdminSeatsRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCatalogIdRoute: typeof AdminAdminCatalogIdRoute
  AdminAdminCatalogIndexRoute: typeof AdminAdminCatalogIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminFinesRoute: AdminAdminFinesRoute,
  AdminAdminIssuesRoute: AdminAdminIssuesRoute,
  AdminAdminLostBooksRoute: AdminAdminLostBooksRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminRequestsRoute: AdminAdminRequestsRoute,
  AdminAdminReservationsRoute: AdminAdminReservationsRoute,
  AdminAdminSeatsRoute: AdminAdminSeatsRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCatalogIdRoute: AdminAdminCatalogIdRoute,
  AdminAdminCatalogIndexRoute: AdminAdminCatalogIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentStudentFinesRoute: typeof StudentStudentFinesRoute
  StudentStudentLostBooksRoute: typeof StudentStudentLostBooksRoute
  StudentStudentMyBooksRoute: typeof StudentStudentMyBooksRoute
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
  StudentStudentReservationsRoute: typeof StudentStudentReservationsRoute
  StudentStudentSeatsRoute: typeof StudentStudentSeatsRoute
  StudentStudentIndexRoute: typeof StudentStudentIndexRoute
  StudentStudentCatalogIdRoute: typeof StudentStudentCatalogIdRoute
  StudentStudentCatalogIndexRoute: typeof StudentStudentCatalogIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentFinesRoute: StudentStudentFinesRoute,
  StudentStudentLostBooksRoute: StudentStudentLostBooksRoute,
  StudentStudentMyBooksRoute: StudentStudentMyBooksRoute,
  StudentStudentProfileRoute: StudentStudentProfileRoute,
  StudentStudentReservationsRoute: StudentStudentReservationsRoute,
  StudentStudentSeatsRoute: StudentStudentSeatsRoute,
  StudentStudentIndexRoute: StudentStudentIndexRoute,
  StudentStudentCatalogIdRoute: StudentStudentCatalogIdRoute,
  StudentStudentCatalogIndexRoute: StudentStudentCatalogIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
